### ISSUE TITLE
corrigir css divergente

### ISSUE THREAD

**Issue by nalomysouza** [secultce/wp-consulta-publica#3]
ao instalar o thema no repositório da secult, não está carregando as cores 
com no http://culturadigital.br/cpe/
![erro -css](https://user-images.githubusercontent.com/2711728/55974068-3f95b300-5c5d-11e9-9240-88d3fcec1e4c.png)

**Comment by benrainir** [comment]
O problema que o wordpress e o tema foram atualizados e o css deu alguns problemas, vamos realizar os ajustes necessários
